modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-DualWither//issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-dual-wither"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="sbmdualwither" #mandatory
version="0.1.0" #mandatory
displayName="SBM Dual Wither" #mandatory
description='''Spawns additional wither bosses for any vanilla spawned boss''' #mandatory

[[dependencies.sbmdualwither]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbmdualwither]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"